BEGIN {
    FS = "|"
    print "/* Generated by tools/gen-patterns.awk from patterns.def. */"
    print "#ifndef PATTERN_META_H"
    print "#define PATTERN_META_H"
    print ""
}

/^[[:space:]]*($|#)/ {
    next
}

NF >= 2 {
    name = $1
    pattern = $2
    jump_offset = $3

    if (name !~ /^[A-Za-z_][A-Za-z0-9_]*$/) {
        printf("gen-patterns: invalid macro name '%s' at line %d\n",
               name, NR) > "/dev/stderr"
        exit 1
    }
    if (pattern ~ /["\\]/) {
        printf("gen-patterns: pattern for '%s' has unescapable char\n",
               name) > "/dev/stderr"
        exit 1
    }

    len = 0
    for (i = 1; i <= length(pattern); i++) {
        ch = substr(pattern, i, 1)
        if (ch !~ /[[:space:]]/)
            len++
    }

    printf("#define %s_PATTERN \"%s\"\n", name, pattern)
    printf("#define %s_PATTERN_LEN %d\n", name, len)
    if (jump_offset != "")
        printf("#define %s_PATTERN_JUMP_OFFSET %s\n", name, jump_offset)
    print ""
}

END {
    print "#define LDINC_INCREMENT_OFFSET ILOAD_PATTERN_LEN"
    print ""
    print "#endif"
}
